### ISSUE TITLE
Flabbergast-diff broken on MacOS X

### ISSUE THREAD

**Issue by ZeissS** [flabbergast-config/flabbergast#52]
Using `flabbergast-diff` on Mac Os X just issues the usage of `mktemp`.  Installed via .pkg from the website.

```
$ flabbergast-diff test.o_o
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix

$ mktemp -d
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

https://github.com/flabbergast-config/flabbergast/blob/0efd585dbdc800b56e507f61dbb34f64cadcb66a/flabbergast-diff#L49 states that only `mktemp -d` is called, which seems to not work on Mac OS. I changed that line to be `mktemp -d -t flabbergast-diff` which made it work. 

The option `-t` reads like this in the manpage:

```
     -t prefix
             Generate a template (using the supplied prefix and TMPDIR if set) to create a filename template.
```

I am not sure if this change is compatible with non-mac environments.

**Comment by apmasell** [comment]
Thank you for your bug report.

Using `-t` isn't portable to non-MacOS platforms (standard joke about UNIX portability). I've found an invocation that seems to work on both MacOS and Linux. Changed in: b4884a2dff1596d8885acb47c6b54a8e694ff616

I will be making a new release within a week.

**Comment by ZeissS** [comment]
Ack, can confirm. That change gives me a temp path too.

**Comment by apmasell** [comment]
Great! Thanks. :-)
