### ISSUE TITLE
Hard to scratch-build

### ISSUE THREAD

**Issue by vatine** [flabbergast-config/flabbergast#61]
Looks like the PPA is no longer available and bootstrap-from-web seems to be unable to find a bootstrappable base.

**Comment by apmasell** [comment]
I've updated the PPA to have packages for Bionic and Focal. I'm not sure why `bootstrap-from-web` isn't working for you. It there's a package for the latest version of head: http://docs.flabbergast.org/bootstrap/bootstrap-7aaa90b04586fb217e74220a34accc9511d03c37.tar.bz2
Which commit are you on?

You can also pull working JARs from Maven: https://search.maven.org/search?q=g:com.github.apmasell.flabbergast

**Comment by vatine** [comment]
The git repo is a `git clone` from yesterday.

```
$ git log --pretty=format:%H "HEAD~5..HEAD"
7aaa90b04586fb217e74220a34accc9511d03c37
455632b6e9f5b254686741acab2a6a6e8a52195d
6f7d2306734159f795f369181fc2c4e76cb0ee65
dd9d1d35d3b1f1527e6656a3b5fcd8ab2147ba0b
94933733c341bbc81bb9cb7ceb63b8b6400b825f
```

With hashes printed during the bootstrapping (and limit cutr down to 10):
```
$ ./bootstrap-from-web 
DEBUG: HASH is 7aaa90b04586fb217e74220a34accc9511d03c37
DEBUG: HASH is 455632b6e9f5b254686741acab2a6a6e8a52195d
DEBUG: HASH is 6f7d2306734159f795f369181fc2c4e76cb0ee65
DEBUG: HASH is dd9d1d35d3b1f1527e6656a3b5fcd8ab2147ba0b
DEBUG: HASH is 94933733c341bbc81bb9cb7ceb63b8b6400b825f
DEBUG: HASH is 09cc07693c45b1367a3cfd89c4ebe35bf4680c55
DEBUG: HASH is beb37a16c0b31e90965ab39c7b09c0bc4834f650
DEBUG: HASH is fa32d29b1aac3408f58ba48d020f29f533654d78
DEBUG: HASH is e4bbb9992768e6e9c4e6e4950c804e28688a0747
DEBUG: HASH is 46892c73e907dca393227f5e5c9c1330a203a8a3
Could not find a boostrappable revision.
```

Weirdly, when I do what I would've expected the script to do, I do get a tarball:
```
$ curl -s http://docs.flabbergast.org/bootstrap/bootstrap-7aaa90b04586fb217e74220a34accc9511d03c37.tar.bz2 | tar xvjf -
flabbergast_sql.7
platform/jvm/compiler-jvm.a
platform/jvm/runtime/flabbergast/db-jvm.java
```

I have NO idea why the web boostrap is doing what it does.

**Comment by apmasell** [comment]
Well, that's super weird. I'm not sure either. If you have the bootstrap package, you can extract it on top of the build directory and it should be fine.

**Comment by vatine** [comment]
I'll try blowing my clone out of the way and try again. Worst case, it doesn't change the current state of things on my end.

**Comment by vatine** [comment]
```
$ vi bootstrap-from-web 
$ ./bootstrap-from-web 
Bootstrapped to revision 7aaa90b04586fb217e74220a34accc9511d03c37.
$ git diff bootstrap-from-web
diff --git a/bootstrap-from-web b/bootstrap-from-web
index df547e7..5a06ff4 100755
--- a/bootstrap-from-web
+++ b/bootstrap-from-web
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-URL="http://docs.flabbergast.org/bootstrap/"
+URL="http://docs.flabbergast.org/bootstrap"
 LIMIT=20
 
 set -eu
```

**Comment by apmasell** [comment]
Ah. I see.

**Comment by vatine** [comment]
After many attempts, I now seem to have a runnable flabbergast, so I shall quietly continue with my plans (but not implementing a lisp interpreter, this time).
